### ISSUE TITLE
Transitions in a cycle

### ISSUE THREAD

**Issue by dsolgalov** [JuzTosS/AnimationsDemo#1]
День добрый!

К сожалению, не мог оставить комментарий на хабре, т.к. статья уже давняя. Решил написать тут.
Собственно такой вопрос:
можно ли как-то реализовать последовательные переходы между N сценами без нажатия соответствующих кнопок, используя Transitions Framework. То есть зациклить эти переходы, чтобы получилась анимация.

Заранее благодарю.
PS: я пытался делать последовательные вызовы TransitionManager.go() / TransitionManager.beginDelayedTransition - но это не привело к ожидаемому результату....

**Comment by JuzTosS** [comment]
День добрый :)
Возможно поможет назначить листенер на transition и по завершению запустить свою анимацию. (Если я правильно понял кейс)
```
        val myTransition = AutoTransition()
        myTransition.addListener(object : Transition.TransitionListener {
            override fun onTransitionEnd(transition: Transition?) {
                TransitionManager.go(nextScene)
            }

            override fun onTransitionResume(transition: Transition?) {
            }

            override fun onTransitionPause(transition: Transition?) {
            }

            override fun onTransitionCancel(transition: Transition?) {
            }

            override fun onTransitionStart(transition: Transition?) {
            }
        })
        TransitionManager.go(sceneB, myTransition)
```

**Comment by dsolgalov** [comment]
@JuzTosS , спасибо за идею. Это то, что нужно :)
Жаль, что google не предоставляет возможность pending транзишенов "из коробки". 
поэтому и приходится искать вот такие обходные пути :)
